### PR TITLE
Fix for v5.0.0 changes in adapt-contrib-assessmentResults

### LINKED ISSUE #2: Broken by v5.0.0 changes in adapt-contrib-assessmentResults
Specifically this change: https://github.com/adaptlearning/adapt-contrib-assessmentResults/commit/02dfab9b8fbbb4a2c6779f3f89639ab3cbe65da1

### PR DESCRIPTION
**Pull request by chris-steele**
Fixes #2

### CODE REVIEW

**Comment by oliverfoster** [comment]
Switch to es6 modules whilst you're here?

**Review by guywillis — APPROVED** [review]
👍

**Review by joe-replin — APPROVED** [review]

**Comment by joe-replin** [comment]
I would like to add v1 AAT schemas to this plug-in. Trying to get this approved & merged. I've tested this in the AAT.

**Comment by chris-steele** [comment]
@joe-replin do you fancy converting this to ES6? Might be a good exercise and happy to support you on this if you need.

**Comment by joe-replin** [comment]
@chris-steele, sure thing. Should both PRs go through first? I have schema updates here:
https://github.com/cgkineo/adapt-assLearning/pull/5

Seems like there are conflicts between master and both PRs. Do you think it would be good to resolve, commit and then do the ES6 conversion?

**Comment by chris-steele** [comment]
Oops, looks we've both already done the ES6 changes 😆 

Can you edit bower.json in [your PR](https://github.com/cgkineo/adapt-assLearning/pull/5) by taking bower.json from master and amend it to bump the fw+plugin dependencies as your PR requires?

Then your PR is good to be merged and I can delete mine.

**Pull request merged**
